Event/Event/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework.routers import DefaultRouter
from users_app import views as user_views
from event_app import views as event_views

router = DefaultRouter()
router.register(r'profiles', user_views.UserProfileViewSet)
router.register(r'events', event_views.EventViewSet)

schema_view = get_schema_view(
    openapi.Info(
        title="Your API",
        default_version='v1',
        description="API description",
        terms_of_service="https://www.myapp.com/terms/",
        contact=openapi.Contact(email="contact@myapp.com"),
        license=openapi.License(name="My License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path('swagger.json', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('users/', include(('users_app.urls', 'users_app'), namespace='users_app')),
    path('', include(('event_app.urls', 'event_app'), namespace='event_app')),
]

Event/event_app/urls.py
from django.urls import path

from .views import EventListView, EventCreateView, EventUpdateView, EventDeleteView, JoinEventView, UnjoinEventView, \
    EventDetailView

urlpatterns = [
    path('', EventListView.as_view(), name='events'),
    path('events/create/', EventCreateView.as_view(), name='event_create'),
    path('events/<int:pk>/update/', EventUpdateView.as_view(), name='event_update'),
    path('events/<int:pk>/', EventDetailView.as_view(), name='event_detail'),
    path('events/<int:pk>/delete/', EventDeleteView.as_view(), name='event_delete'),
    path('events/<int:event_id>/join/', JoinEventView.as_view(), name='join_event'),
    path('events/<int:event_id>/unjoin/', UnjoinEventView.as_view(), name='unjoin_event'),
]

Event/users_app/urls.py
from django.urls import path
from .views import CustomLoginView, CustomLogoutView, register, profile_detail, ProfileUpdate, ProfileDelete

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('register/', register, name='register'),
    path('profile/<int:pk>/', profile_detail, name='profile_detail'),
    path('profile/<int:pk>/edit/', ProfileUpdate.as_view(), name='profile_edit'),
    path('profile/<int:pk>/delete/', ProfileDelete.as_view(), name='profile_delete'),
]

Event/templates/events/event_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
<div class="delete-page">
  <h1>Delete Event</h1>
  <p>Are you sure you want to delete "{{ object.title }}"?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Yes</button>
  </form>
  <a href="{% url 'event_app:event_detail' object.pk %}">Cancel</a>
</div>
{% endblock %}

Event/templates/events/event_detail.html
{% extends "base_generic.html" %}

{% block content %}
<div class="event-detail" data-event-id="{{ event.id }}">
  <h2>{{ event.title }}</h2>
  <p>{{ event.text }}</p>
  <p>Created at: {{ event.date_created }}</p>
  <p>Created by: {{ event.creator.username }}</p>

  {% if user.is_authenticated %}
    {% if is_creator %}
      <a href="{% url 'event_app:event_update' event.id %}">Edit</a>
      <a href="{% url 'event_app:event_delete' event.id %}">Delete</a>
    {% else %}
      {% if user in event.participants.all %}
        <form method="post" action="{% url 'event_app:unjoin_event' event.id %}" class="ajax-form" id="unjoinForm">
          {% csrf_token %}
          <button type="submit">Отменить участие</button>
        </form>
      {% else %}
        <form method="post" action="{% url 'event_app:join_event' event.id %}" class="ajax-form" id="joinForm">
          {% csrf_token %}
          <button type="submit">Участвовать</button>
        </form>
      {% endif %}
    {% endif %}
  {% endif %}

  <hr/>

  {% if event.participants.all %}
  <p>Participants:</p>
  <ul>
    {% for participant in event.participants.all %}
      <li>
        {% with profile=participant.userprofile %}
          {% if profile %}
            <a href="{% url 'users_app:profile_detail' profile.pk  %}">
              {{ participant.username }}
            </a>
          {% else %}
            {{ participant.username }}
          {% endif %}
        {% endwith %}
      </li>
    {% endfor %}
  </ul>
{% else %}
  <p>No participants yet.</p>
{% endif %}


</div>

{% endblock %}

Event/templates/events/event_form.html
{% extends "base_generic.html" %}

{% block content %}
<div class="form-container">
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}


    <button type="submit">Save changes</button>
  </form>
</div>
{% endblock %}

Event/templates/events/event_list.html
{% extends "base_generic.html" %}

{% block content %}
<div class="main-content">
  <div class="event-list">
    {% if user.is_authenticated %}
      <a href="{% url 'event_app:event_create' %}" class="create-link">Create new event</a>
    {% endif %}
    {% if events %}
      <ul id="event-list-ul">
      {% for event in events %}

          <li class="event-list-item" data-event-id="{{ event.pk }}">
              <a href="{% url 'event_app:event_detail' event.pk %}">{{ event.title }}</a>
          </li>

      {% endfor %}
      </ul>
    {% else %}
      <p>No events available at the moment.</p>
    {% endif %}
  </div>
</div>
{% endblock %}