Event/Event/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework.routers import DefaultRouter
from users_app import views as user_views
from event_app import views as event_views

router = DefaultRouter()
router.register(r'profiles', user_views.UserProfileViewSet)
router.register(r'events', event_views.EventViewSet)

schema_view = get_schema_view(
    openapi.Info(
        title="Your API",
        default_version='v1',
        description="API description",
        terms_of_service="https://www.myapp.com/terms/",
        contact=openapi.Contact(email="contact@myapp.com"),
        license=openapi.License(name="My License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path('swagger.json', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('users/', include(('users_app.urls', 'users_app'), namespace='users_app')),
    path('', include(('event_app.urls', 'event_app'), namespace='event_app')),
]

Event/event_app/urls.py
from django.urls import path

from .views import EventListView, EventCreateView, EventUpdateView, EventDeleteView, JoinEventView, UnjoinEventView, \
    EventDetailView

urlpatterns = [
    path('', EventListView.as_view(), name='events'),
    path('events/create/', EventCreateView.as_view(), name='event_create'),
    path('events/<int:pk>/update/', EventUpdateView.as_view(), name='event_update'),
    path('events/<int:pk>/', EventDetailView.as_view(), name='event_detail'),
    path('events/<int:pk>/delete/', EventDeleteView.as_view(), name='event_delete'),
    path('events/<int:event_id>/join/', JoinEventView.as_view(), name='join_event'),
    path('events/<int:event_id>/unjoin/', UnjoinEventView.as_view(), name='unjoin_event'),
]

Event/users_app/urls.py
from django.urls import path
from .views import CustomLoginView, CustomLogoutView, register, profile_detail, ProfileUpdate, ProfileDelete

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('register/', register, name='register'),
    path('profile/<int:pk>/', profile_detail, name='profile_detail'),
    path('profile/<int:pk>/edit/', ProfileUpdate.as_view(), name='profile_edit'),
    path('profile/<int:pk>/delete/', ProfileDelete.as_view(), name='profile_delete'),
]

Event/templates/base_generic.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- Bootstrap CSS -->
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">

  <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
  <title>Events Site</title>
</head>
<body>
  <header>
    <div class="navbar">
      <div>
      {% if request.resolver_match.url_name != 'events' %}
        <a href="{% url 'event_app:events' %}">Events List</a>
      {% endif %}
    </div>
      <div>
        {% if user.is_authenticated %}
          <span>Username:
            {% if user.userprofile.pk %}
              <a href="{% url 'users_app:profile_detail' user.userprofile.pk %}">{{ user.username }}</a>
            {% else %}
              {{ user.username }}
            {% endif %}
          </span>
          <a href="{% url 'users_app:logout' %}">Logout</a>
        {% else %}
          <a href="{% url 'users_app:login' %}"> Login </a>
          <a href="{% url 'users_app:register' %}"> Register </a>
        {% endif %}
      </div>
    </div>
  </header>

  <main>
    <div class="main-content">
      {% block content %}
      {% endblock %}
    </div>
  </main>

  <footer>
      <!-- Здесь может быть подвал -->
  </footer>

  <!-- Модальное окно для сообщений -->
  <div class="modal fade" id="errorMessageModal" tabindex="-1" aria-labelledby="errorMessageModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="errorMessageModalLabel">Ошибка</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <!-- Сообщение об ошибке здесь -->
        {% if messages %}
            {% for message in messages %}
                {% if message.tags == "error" %}
                    <p>{{ message }}</p>
                {% endif %}
            {% endfor %}
        {% endif %}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
    </div>
  </div>

  <!-- Bootstrap и jQuery -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

  <script src="{% static 'scripts.js' %}"></script>
</body>
</html>