Event/Event/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework.routers import DefaultRouter
from users_app import views as user_views
from event_app import views as event_views

router = DefaultRouter()
router.register(r'profiles', user_views.UserProfileViewSet)
router.register(r'events', event_views.EventViewSet)

schema_view = get_schema_view(
    openapi.Info(
        title="Your API",
        default_version='v1',
        description="API description",
        terms_of_service="https://www.myapp.com/terms/",
        contact=openapi.Contact(email="contact@myapp.com"),
        license=openapi.License(name="My License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path('swagger.json', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('users/', include(('users_app.urls', 'users_app'), namespace='users_app')),
    path('', include(('event_app.urls', 'event_app'), namespace='event_app')),
]

Event/event_app/urls.py
from django.urls import path

from .views import EventListView, EventCreateView, EventUpdateView, EventDeleteView, JoinEventView, UnjoinEventView, \
    EventDetailView

urlpatterns = [
    path('', EventListView.as_view(), name='events'),
    path('events/create/', EventCreateView.as_view(), name='event_create'),
    path('events/<int:pk>/update/', EventUpdateView.as_view(), name='event_update'),
    path('events/<int:pk>/', EventDetailView.as_view(), name='event_detail'),
    path('events/<int:pk>/delete/', EventDeleteView.as_view(), name='event_delete'),
    path('events/<int:event_id>/join/', JoinEventView.as_view(), name='join_event'),
    path('events/<int:event_id>/unjoin/', UnjoinEventView.as_view(), name='unjoin_event'),
]

Event/users_app/urls.py
from django.urls import path
from .views import CustomLoginView, CustomLogoutView, register, profile_detail, ProfileUpdate, ProfileDelete

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('register/', register, name='register'),
    path('profile/<int:pk>/', profile_detail, name='profile_detail'),
    path('profile/<int:pk>/edit/', ProfileUpdate.as_view(), name='profile_edit'),
    path('profile/<int:pk>/delete/', ProfileDelete.as_view(), name='profile_delete'),
]

Event/templates/users/login.html
{% extends "base_generic.html" %}

{% block content %}
<div class="login-page">
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
  <p>Don't have an account? <a href="{% url 'users_app:register' %}">Register</a></p>
</div>
{% endblock %}

Event/templates/users/profile_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
<div class="delete-profile-page">
  <h2>Are you sure you want to delete your profile?</h2>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Yes, delete</button>
  </form>
  <a href="{% url 'users_app:profile_detail' object.pk %}">Cancel</a>
</div>
{% endblock %}

Event/templates/users/profile_detail.html
{% extends "base_generic.html" %}

{% block title %}User Profile{% endblock %}

{% block content %}
  <div class="profile-page">
  <h2>Profile Detail</h2>

  <div>
    <strong>Username:</strong> {{ profile.user.username }}
  </div>

  <div>
    <strong>First Name:</strong> {{ profile.user.first_name }}
  </div>

  <div>
    <strong>Last Name:</strong> {{ profile.user.last_name }}
  </div>

  <div>
    <strong>Date of birth:</strong> {{ profile.date_of_birth }}
  </div>

  <div>
    <strong>Registration date:</strong> {{ profile.date_registered }}
  </div>

  <h3>Created Events:</h3>
  {% if profile.user.created_events.all %}
    <ul>
      {% for event in profile.user.created_events.all %}
        <li><a href="{% url 'event_app:event_detail' event.pk %}">{{ event.title }}</a></li>
      {% endfor %}
    </ul>
  {% else %}
    <p>This user hasn't created any events yet.</p>
  {% endif %}

  <h3>Participating Events:</h3>
  {% if profile.user.participating_events.all %}
    <ul>
      {% for event in profile.user.participating_events.all %}
        <li><a href="{% url 'event_app:event_detail' event.pk %}">{{ event.title }}</a></li>
      {% endfor %}
    </ul>
  {% else %}
    <p>This user isn't participating in any events yet.</p>
  {% endif %}

    <hr/>

  {% if user == profile.user %}
    <a href="{% url 'users_app:profile_edit' profile.pk %}">Edit Profile</a>
    <a href="{% url 'users_app:profile_delete' profile.pk %}">Delete Profile</a>
  {% endif %}
</div>
{% endblock %}

Event/templates/users/profile_edit.html
{% extends "base_generic.html" %}

{% block content %}
<div class="edit-profile-page">
  <h2>Edit Profile</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save changes</button>
  </form>
</div>
{% endblock %}

Event/templates/users/register.html
{% extends "base_generic.html" %}

{% block content %}
<div class="registration-page">
  <h2>Register</h2>
  <form method="post">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <button type="submit">Register</button>
  </form>
  <p>Already have an account? <a href="{% url 'users_app:login' %}">Login</a></p>
</div>
{% endblock %}